/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oop_finals;

/**
 *
 * @author Admin
 */
import java.sql.*;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;


public class student_bookappointment extends javax.swing.JFrame {
    private CustomDateEvaluator currentEvaluator = null;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(student_bookappointment.class.getName());

    private Connection conn;
    private static final String DB_URL = "jdbc:mysql://localhost:3306/guidance_appointment_system";
    private static final String DB_USER = "root";
    private static final String DB_PASS = "";

    // 3. CONSTRUCTOR (modify the existing one)
    public student_bookappointment() {
        initComponents();
        loadSpecializations(); // ADD THIS LINE
        counselordetails.setEditable(false);
        counselordetails.setText("Select a specialization and counselor to view details.");

        // Set minimum selectable date to today
        schedulecalendar.setMinSelectableDate(new java.util.Date());

        // Add property change listener to calendar
        schedulecalendar.addPropertyChangeListener("calendar", evt -> {
            updateCalendarForSelectedCounselor();
        });
    }
    /**
     * Creates new form student_bookappointment
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        bookappointment = new javax.swing.JButton();
        viewprofile = new javax.swing.JButton();
        myappointmets = new javax.swing.JButton();
        profilelogo = new javax.swing.JLabel();
        appointmentlogo = new javax.swing.JLabel();
        booklogo = new javax.swing.JLabel();
        welcome = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        logo_home = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        book = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        nextpage = new javax.swing.JButton();
        specialization = new javax.swing.JComboBox<>();
        counselor = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        counselordetails = new javax.swing.JTextArea();
        select = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        schedulecalendar = new com.toedter.calendar.JCalendar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(38, 36, 68));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        bookappointment.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bookappointment.setText("BOOK APPOINTMENT");
        bookappointment.setBorderPainted(false);
        bookappointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookappointmentActionPerformed(evt);
            }
        });

        viewprofile.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        viewprofile.setText("VIEW PROFILE");
        viewprofile.setBorderPainted(false);
        viewprofile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewprofileActionPerformed(evt);
            }
        });

        myappointmets.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        myappointmets.setText("MY APPOINTMENTS");
        myappointmets.setBorderPainted(false);
        myappointmets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myappointmetsActionPerformed(evt);
            }
        });

        profilelogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oop_finals/images/profile.png"))); // NOI18N
        profilelogo.setText("icon");

        appointmentlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oop_finals/images/appointments.png"))); // NOI18N
        appointmentlogo.setText("icon");

        booklogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oop_finals/images/book appointment.png"))); // NOI18N
        booklogo.setText("icon");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(booklogo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bookappointment)
                .addGap(42, 42, 42)
                .addComponent(appointmentlogo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(myappointmets)
                .addGap(49, 49, 49)
                .addComponent(profilelogo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewprofile)
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookappointment)
                    .addComponent(profilelogo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(myappointmets)
                    .addComponent(viewprofile)
                    .addComponent(booklogo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(appointmentlogo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        welcome.setForeground(new java.awt.Color(255, 255, 255));
        welcome.setText("WELCOME,");

        user.setForeground(new java.awt.Color(255, 255, 255));
        user.setText("USER!");

        logout.setBackground(new java.awt.Color(204, 0, 0));
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("LOGOUT");
        logout.setBorderPainted(false);
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        logo_home.setBackground(new java.awt.Color(38, 36, 68));
        logo_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oop_finals/images/logo.png"))); // NOI18N
        logo_home.setBorderPainted(false);
        logo_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logo_homeActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 195, 51));
        jLabel6.setText("SELECT COUNSELOR");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        book.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        book.setText("BOOK APPOINTMENT");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oop_finals/images/book appointment.png"))); // NOI18N
        jLabel1.setText("icon");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(book)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(book)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        nextpage.setBackground(new java.awt.Color(255, 195, 51));
        nextpage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nextpage.setForeground(new java.awt.Color(255, 255, 255));
        nextpage.setText("NEXT");
        nextpage.setBorderPainted(false);
        nextpage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextpageActionPerformed(evt);
            }
        });

        specialization.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        specialization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                specializationActionPerformed(evt);
            }
        });

        counselor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        counselor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                counselorActionPerformed(evt);
            }
        });

        counselordetails.setColumns(20);
        counselordetails.setRows(5);
        jScrollPane2.setViewportView(counselordetails);

        select.setText("Select");
        select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 195, 51));
        jLabel3.setText("SPECIALIZATION");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 195, 51));
        jLabel8.setText("COUNSELOR");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(logo_home, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(welcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(user)
                .addGap(37, 37, 37)
                .addComponent(logout)
                .addGap(38, 38, 38))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nextpage, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(specialization, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(counselor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addGap(0, 0, Short.MAX_VALUE))))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                                            .addComponent(select, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(schedulecalendar, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(40, 40, 40))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(logout)
                            .addComponent(welcome)
                            .addComponent(user)))
                    .addComponent(logo_home, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(specialization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(counselor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(select))
                    .addComponent(schedulecalendar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(nextpage)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bookappointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookappointmentActionPerformed
        // TODO add your handling code here:
        student_bookappointment a = new student_bookappointment();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bookappointmentActionPerformed

    private void viewprofileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewprofileActionPerformed
        // TODO add your handling code here:
        student_viewprofile b = new student_viewprofile();
        b.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_viewprofileActionPerformed

    private void myappointmetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myappointmetsActionPerformed
        // TODO add your handling code here:
        student_myappointment c = new student_myappointment();
        c.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_myappointmetsActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutActionPerformed

    private void logo_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logo_homeActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new student_dashboard().setVisible(true);
    }//GEN-LAST:event_logo_homeActionPerformed

    private void nextpageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextpageActionPerformed
        // TODO add your handling code here:                                                                             
        String selectedSpecialization = (String) specialization.getSelectedItem();
        String selectedCounselor = (String) counselor.getSelectedItem();

        if (selectedSpecialization == null || selectedSpecialization.equals("-- Select Specialization --")) {
            JOptionPane.showMessageDialog(this, "Please select a specialization before proceeding.",
                    "Selection Required", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (selectedCounselor == null || selectedCounselor.equals("-- Select Counselor --")) {
            JOptionPane.showMessageDialog(this, "Please select a counselor before proceeding.",
                    "Selection Required", JOptionPane.WARNING_MESSAGE);
            return;
        }

        java.util.Date selectedDate = schedulecalendar.getDate();
        if (selectedDate == null) {
            JOptionPane.showMessageDialog(this, "Please select a date from the calendar.",
                    "Date Required", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Get counselor ID
        int counselorId = getSelectedCounselorId();

        if (counselorId == -1) {
            JOptionPane.showMessageDialog(this, "Error retrieving counselor information.",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Proceed to next page
        student_bookappointment2nd d = new student_bookappointment2nd();
        d.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_nextpageActionPerformed

    private void selectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectActionPerformed
        // TODO add your handling code here:
        String selectedSpecialization = (String) specialization.getSelectedItem();
        String selectedCounselor = (String) counselor.getSelectedItem();
        
        if (selectedSpecialization == null || selectedSpecialization.equals("-- Select Specialization --")) {
            JOptionPane.showMessageDialog(this, "Please select a specialization first.",
                    "Selection Required", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (selectedCounselor == null || selectedCounselor.equals("-- Select Counselor --")) {
            JOptionPane.showMessageDialog(this, "Please select a counselor.",
                    "Selection Required", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int confirm = JOptionPane.showConfirmDialog(this,
                "You have selected:\nCounselor: " + selectedCounselor + 
                "\nSpecialization: " + selectedSpecialization + "\n\nProceed?",
                "Confirm Selection",
                JOptionPane.YES_NO_OPTION);
        
        if (confirm == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this, "Counselor selected successfully!",
                    "Success", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_selectActionPerformed

    private void counselorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_counselorActionPerformed
        // TODO add your handling code here:
        String selectedCounselor = (String) counselor.getSelectedItem();

    if (selectedCounselor != null && !selectedCounselor.equals("-- Select Counselor --")) {
        displayCounselorInfo(selectedCounselor);

        // Apply calendar restrictions for selected counselor
        int counselorId = getSelectedCounselorId();
        if (counselorId != -1) {
            applyCounselorScheduleToCalendar(counselorId);
        }
    } else {
        counselordetails.setText("Select a counselor to view details.");
        
        // Remove evaluator when no counselor selected
        if (currentEvaluator != null) {
            try {
                schedulecalendar.getDayChooser().removeDateEvaluator(currentEvaluator);
                currentEvaluator = null;
                schedulecalendar.getDayChooser().setCalendar(schedulecalendar.getCalendar());
                schedulecalendar.updateUI();
            } catch (Exception e) {
                // Ignore if removal fails
            }
        }
    }
    }//GEN-LAST:event_counselorActionPerformed

    private void specializationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specializationActionPerformed
        // TODO add your handling code here:
        String selectedSpecialization = (String) specialization.getSelectedItem();
        
        if (selectedSpecialization != null && !selectedSpecialization.equals("-- Select Specialization --")) {
            loadCounselorsBySpecialization(selectedSpecialization);
        } else {
            DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
            model.addElement("-- Select Counselor --");
            counselor.setModel(model);
            counselordetails.setText("Select a specialization and counselor to view details.");
        }
    }//GEN-LAST:event_specializationActionPerformed

    private Connection getConnection() {
        try {
            if (conn == null || conn.isClosed()) {
                Class.forName("com.mysql.cj.jdbc.Driver");
                conn = DriverManager.getConnection(DB_URL, DB_USER, DB_PASS);
            }
            return conn;
        } catch (ClassNotFoundException | SQLException e) {
            logger.log(java.util.logging.Level.SEVERE, "Database connection error", e);
            JOptionPane.showMessageDialog(this, "Database connection failed: " + e.getMessage(),
                    "Connection Error", JOptionPane.ERROR_MESSAGE);
            return null;
        }
    }
    
    private void loadSpecializations() {
        try {
            Connection connection = getConnection();
            if (connection == null) return;
            
            String query = "SELECT DISTINCT specialization FROM counselors WHERE status = 'Active' ORDER BY specialization";
            PreparedStatement pst = connection.prepareStatement(query);
            ResultSet rs = pst.executeQuery();
            
            DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
            model.addElement("-- Select Specialization --");
            
            while (rs.next()) {
                model.addElement(rs.getString("specialization"));
            }
            
            specialization.setModel(model);
            rs.close();
            pst.close();
        } catch (SQLException e) {
            logger.log(java.util.logging.Level.SEVERE, "Error loading specializations", e);
            JOptionPane.showMessageDialog(this, "Error loading specializations: " + e.getMessage(),
                    "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void loadCounselorsBySpecialization(String specialization) {
        try {
            Connection connection = getConnection();
            if (connection == null) return;
            
            String query = "SELECT counselor_id, name FROM counselors WHERE specialization = ? AND status = 'Active' ORDER BY name";
            PreparedStatement pst = connection.prepareStatement(query);
            pst.setString(1, specialization);
            ResultSet rs = pst.executeQuery();
            
            DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
            model.addElement("-- Select Counselor --");
            
            while (rs.next()) {
                String counselorDisplay = rs.getString("name");
                model.addElement(counselorDisplay);
            }
            
            counselor.setModel(model);
            counselordetails.setText("");
            
            rs.close();
            pst.close();
        } catch (SQLException e) {
            logger.log(java.util.logging.Level.SEVERE, "Error loading counselors", e);
            JOptionPane.showMessageDialog(this, "Error loading counselors: " + e.getMessage(),
                    "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void displayCounselorInfo(String counselorName) {
        try {
            Connection connection = getConnection();
            if (connection == null) return;
            
            String query = "SELECT * FROM counselors WHERE name = ? AND status = 'Active'";
            PreparedStatement pst = connection.prepareStatement(query);
            pst.setString(1, counselorName);
            ResultSet rs = pst.executeQuery();
            
            if (rs.next()) {
                StringBuilder info = new StringBuilder();
                info.append("═══════════════════════════════════\n");
                info.append("           COUNSELOR DETAILS\n");
                info.append("═══════════════════════════════════\n\n");
                info.append("Name: ").append(rs.getString("name")).append("\n");
                info.append("Specialization: ").append(rs.getString("specialization")).append("\n");
                info.append("Email: ").append(rs.getString("email")).append("\n");
                info.append("License Number: ").append(rs.getString("license_number")).append("\n");
                info.append("Status: ").append(rs.getString("status")).append("\n\n");
                info.append("═══════════════════════════════════\n");
                
                counselordetails.setText(info.toString());
            } else {
                counselordetails.setText("Counselor information not found.");
            }
            
            rs.close();
            pst.close();
        } catch (SQLException e) {
            logger.log(java.util.logging.Level.SEVERE, "Error loading counselor info", e);
            JOptionPane.showMessageDialog(this, "Error loading counselor information: " + e.getMessage(),
                    "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public int getSelectedCounselorId() {
        try {
            String selectedCounselor = (String) counselor.getSelectedItem();
            if (selectedCounselor == null || selectedCounselor.equals("-- Select Counselor --")) {
                return -1;
            }
            
            Connection connection = getConnection();
            if (connection == null) return -1;
            
            String query = "SELECT counselor_id FROM counselors WHERE name = ? AND status = 'Active'";
            PreparedStatement pst = connection.prepareStatement(query);
            pst.setString(1, selectedCounselor);
            ResultSet rs = pst.executeQuery();
            
            int counselorId = -1;
            if (rs.next()) {
                counselorId = rs.getInt("counselor_id");
            }
            
            rs.close();
            pst.close();
            return counselorId;
            
        } catch (SQLException e) {
            logger.log(java.util.logging.Level.SEVERE, "Error getting counselor ID", e);
            return -1;
        }
    }
    
    @Override
    public void dispose() {
        try {
            if (conn != null && !conn.isClosed()) {
                conn.close();
            }
        } catch (SQLException e) {
            logger.log(java.util.logging.Level.SEVERE, "Error closing connection", e);
        }
        super.dispose();
    }
    
    private void updateCalendarForSelectedCounselor() {
    int counselorId = getSelectedCounselorId();

    if (counselorId == -1) {
        return; // No counselor selected
    }

    java.util.Date selectedDate = schedulecalendar.getDate();

    if (selectedDate == null) {
        return;
    }

    // Check if the selected date is available
    if (!CalendarHelper.isDateAvailable(counselorId, selectedDate)) {
        // Get the day name for better message
        java.util.Calendar cal = java.util.Calendar.getInstance();
        cal.setTime(selectedDate);
        String[] days = {"", "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"};
        String dayName = days[cal.get(java.util.Calendar.DAY_OF_WEEK)];

        JOptionPane.showMessageDialog(this,
            "The counselor is not available on " + dayName + "s or this specific date is blocked.\nPlease select another date.",
            "Date Unavailable",
            JOptionPane.WARNING_MESSAGE);

        // Clear the selection by updating UI instead of setting to null
        schedulecalendar.getDayChooser().setDay(schedulecalendar.getDayChooser().getDay());
    }
}
    
    private void applyCounselorScheduleToCalendar(int counselorId) {
    try {
        // Remove old evaluator if it exists
        if (currentEvaluator != null) {
            try {
                schedulecalendar.getDayChooser().removeDateEvaluator(currentEvaluator);
            } catch (Exception e) {
                // Ignore if removal fails
            }
        }
        
        // Create and add new evaluator
        currentEvaluator = new CustomDateEvaluator(counselorId);
        schedulecalendar.getDayChooser().addDateEvaluator(currentEvaluator);
        
        // Force calendar refresh
        schedulecalendar.getDayChooser().setCalendar(schedulecalendar.getCalendar());
        schedulecalendar.updateUI();
        
        // Update text area with schedule info
        displayCounselorSchedule(counselorId);
        
    } catch (Exception e) {
        logger.log(java.util.logging.Level.SEVERE, "Error applying calendar restrictions", e);
    }
}
    
    private void displayCounselorSchedule(int counselorId) {
    try {
        Connection connection = getConnection();
        if (connection == null) return;
        
        // Get counselor basic info
        String infoQuery = "SELECT name, specialization, email, license_number FROM counselors WHERE counselor_id = ?";
        PreparedStatement infoPst = connection.prepareStatement(infoQuery);
        infoPst.setInt(1, counselorId);
        ResultSet infoRs = infoPst.executeQuery();
        
        StringBuilder info = new StringBuilder();
        
        if (infoRs.next()) {
            info.append("═══════════════════════════════════\n");
            info.append("           COUNSELOR DETAILS\n");
            info.append("═══════════════════════════════════\n\n");
            info.append("Name: ").append(infoRs.getString("name")).append("\n");
            info.append("Specialization: ").append(infoRs.getString("specialization")).append("\n");
            info.append("Email: ").append(infoRs.getString("email")).append("\n");
            info.append("License Number: ").append(infoRs.getString("license_number")).append("\n\n");
        }
        
        infoRs.close();
        infoPst.close();
        
        // Get schedule
        String schedQuery = "SELECT day_of_week, start_time, end_time FROM counselor_schedules " +
                           "WHERE counselor_id = ? AND is_available = TRUE ORDER BY " +
                           "FIELD(day_of_week, 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday')";
        PreparedStatement schedPst = connection.prepareStatement(schedQuery);
        schedPst.setInt(1, counselorId);
        ResultSet schedRs = schedPst.executeQuery();
        
        info.append("AVAILABILITY SCHEDULE:\n");
        info.append("───────────────────────────────────\n");
        
        boolean hasSchedule = false;
        while (schedRs.next()) {
            hasSchedule = true;
            String day = schedRs.getString("day_of_week");
            String startTime = schedRs.getString("start_time");
            String endTime = schedRs.getString("end_time");
            
            info.append(String.format("%-10s: %s - %s\n", day, 
                formatTime(startTime), formatTime(endTime)));
        }
        
        if (!hasSchedule) {
            info.append("No schedule available\n");
        }
        
        schedRs.close();
        schedPst.close();
        
        // Get blocked dates
        String blockedQuery = "SELECT blocked_date, reason FROM counselor_blocked_dates " +
                             "WHERE counselor_id = ? AND blocked_date >= CURDATE() ORDER BY blocked_date LIMIT 5";
        PreparedStatement blockedPst = connection.prepareStatement(blockedQuery);
        blockedPst.setInt(1, counselorId);
        ResultSet blockedRs = blockedPst.executeQuery();
        
        info.append("\n");
        if (blockedRs.next()) {
            info.append("UPCOMING BLOCKED DATES:\n");
            info.append("───────────────────────────────────\n");
            do {
                String date = blockedRs.getString("blocked_date");
                String reason = blockedRs.getString("reason");
                info.append(String.format("%s - %s\n", date, 
                    reason != null ? reason : "Not available"));
            } while (blockedRs.next());
        }
        
        blockedRs.close();
        blockedPst.close();
        
        info.append("\n═══════════════════════════════════\n");
        info.append("Note: Unavailable dates are shown\n");
        info.append("in red on the calendar.\n");
        
        counselordetails.setText(info.toString());
        
    } catch (SQLException e) {
        logger.log(java.util.logging.Level.SEVERE, "Error loading counselor schedule", e);
    }
}

// Helper method to format time
private String formatTime(String time) {
    try {
        java.text.SimpleDateFormat inputFormat = new java.text.SimpleDateFormat("HH:mm:ss");
        java.text.SimpleDateFormat outputFormat = new java.text.SimpleDateFormat("hh:mm a");
        java.util.Date date = inputFormat.parse(time);
        return outputFormat.format(date);
    } catch (Exception e) {
        return time;
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new student_bookappointment().setVisible(true));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel appointmentlogo;
    private javax.swing.JLabel book;
    private javax.swing.JButton bookappointment;
    private javax.swing.JLabel booklogo;
    private javax.swing.JComboBox<String> counselor;
    private javax.swing.JTextArea counselordetails;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JButton logo_home;
    private javax.swing.JButton logout;
    private javax.swing.JButton myappointmets;
    private javax.swing.JButton nextpage;
    private javax.swing.JLabel profilelogo;
    private com.toedter.calendar.JCalendar schedulecalendar;
    private javax.swing.JButton select;
    private javax.swing.JComboBox<String> specialization;
    private javax.swing.JLabel user;
    private javax.swing.JButton viewprofile;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
